language: python
arch:
  - amd64
  - ppc64le

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

matrix:
   exclude:
      - python: "pypy"
        arch: ppc64le

install:
  - pip install . --quiet
  - pip install nose --quiet
  - pip install speaklater --quiet

script: nosetests

branches:
  only:
    - master
